### ISSUE TITLE
Add missing Python libraries for Flask

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/operations#63]
in: https://github.com/cmu-delphi/operations/blob/main/dev/docker/python/assets/requirements.txt

add: python-dotenv, flask, orjson, sqlalchemy==1.3.24, others?

ref: https://github.com/cmu-delphi/delphi-epidata/pull/417#issuecomment-833080879

**Comment by sgratzl** [comment]
see https://github.com/cmu-delphi/delphi-epidata/blob/main/requirements.txt and https://github.com/cmu-delphi/delphi-epidata/blob/main/requirements.dev.txt
